{"name": "TC 02 - Delete an assignment", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'selenium.common.exceptions.NoSuchElementException'>", "trace": "self = <test_todo_app_allure.TestToDoActionsApp object at 0x0000018E15AD5E10>\n\n    @allure.title(\"TC 02 - Delete an assignment\")\n    @allure.description(\"Create a new assignment and delete it\")\n    def test_tc02(self):\n        try:\n            self.step_add_task2()\n            self.step_delete_task()\n>           self.step_check_task_delete()\n\ntest_todo_app_allure.py:65: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <test_todo_app_allure.TestToDoActionsApp object at 0x0000018E15AD5E10>\n\n    @allure.step(\"Validate the task was deleted\")\n    def step_check_task_delete(self):\n>       with pytest.raises(NoSuchElementException):\nE       Failed: DID NOT RAISE <class 'selenium.common.exceptions.NoSuchElementException'>\n\ntest_todo_app_allure.py:89: Failed"}, "description": "Create a new assignment and delete it", "steps": [{"name": "Create test task", "status": "passed", "start": 1673096239344, "stop": 1673096239392}, {"name": "Delete a task", "status": "passed", "start": 1673096239393, "stop": 1673096239739}, {"name": "Validate the task was deleted", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'selenium.common.exceptions.NoSuchElementException'>\n", "trace": "  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\PycharmProjects\\Aut_Practice_Py\\Course_interview_questions\\ToDo App\\test_todo_app_allure.py\", line 89, in step_check_task_delete\n    with pytest.raises(NoSuchElementException):\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\_pytest\\python_api.py\", line 984, in __exit__\n    fail(self.message)\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\_pytest\\outcomes.py\", line 194, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1673096239740, "stop": 1673096239749}], "attachments": [{"source": "171a8bca-8687-40c1-b979-e5a6978bc415-attachment.png", "type": "image/png"}], "start": 1673096239344, "stop": 1673096239920, "uuid": "dad131f8-1a20-429b-a37c-6d5efe2d7224", "historyId": "c14ef32e13854b5c934cc42dfeefc51d", "testCaseId": "ab1d7e1d77fb4a71b0068a8498b343ee", "fullName": "test_todo_app_allure.TestToDoActionsApp#test_tc02", "labels": [{"name": "suite", "value": "test_todo_app_allure"}, {"name": "subSuite", "value": "TestToDoActionsApp"}, {"name": "host", "value": "BarLaptop"}, {"name": "thread", "value": "18188-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_todo_app_allure"}]}