{"name": "TC 02-B - Delete a task and check the task was deleted -Success", "status": "failed", "statusDetails": {"message": "Failed: View screen shot", "trace": "self = <test_todo_app_allure.TestToDoActionsApp object at 0x00000185E3E3BE90>\n\n    @allure.title(\"TC 02-B - Delete a task and check the task was deleted -Success\")\n    @allure.description(\"Create a new task and delete it\")\n    def test_tc02(self):\n        try:\n            self.step_add_task2()\n>           self.step_delete_task()\n\ntest_todo_app_allure.py:100: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\na = (<test_todo_app_allure.TestToDoActionsApp object at 0x00000185E3E3BE90>,), kw = {}, __tracebackhide__ = True, params = OrderedDict()\nargs = ['<test_todo_app_allure.TestToDoActionsApp object at 0x00000185E3E3BE90>']\n\n    @wraps(func)\n    def impl(*a, **kw):\n        __tracebackhide__ = True\n        params = func_parameters(func, *a, **kw)\n        args = list(map(lambda x: represent(x), a))\n        with StepContext(self.title.format(*args, **params), params):\n>           return func(*a, **kw)\n\n..\\..\\..\\..\\AppData\\Roaming\\Python\\Python311\\site-packages\\allure_commons\\_allure.py:192: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <test_todo_app_allure.TestToDoActionsApp object at 0x00000185E3E3BE90>\n\n    @allure.step(\"Delete test3\")\n    def step_delete_task(self):\n        action = ActionChains(driver)\n>       task = driver.find_elements(By.CSS_SELECTOR, \".view\")[2]\nE       IndexError: list index out of range\n\ntest_todo_app_allure.py:118: IndexError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_todo_app_allure.TestToDoActionsApp object at 0x00000185E3E3BE90>\n\n    @allure.title(\"TC 02-B - Delete a task and check the task was deleted -Success\")\n    @allure.description(\"Create a new task and delete it\")\n    def test_tc02(self):\n        try:\n            self.step_add_task2()\n            self.step_delete_task()\n            self.step_check_task_delete()\n    \n        except Exception as error:\n            print(error)\n>           pytest.fail(\"View screen shot\")\nE           Failed: View screen shot\n\ntest_todo_app_allure.py:105: Failed"}, "description": "Create a new task and delete it", "steps": [{"name": "Create test3 task", "status": "passed", "start": 1673097207154, "stop": 1673097207200}, {"name": "Delete test3", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\PycharmProjects\\Aut_Practice_Py\\Course_interview_questions\\ToDo App\\test_todo_app_allure.py\", line 118, in step_delete_task\n    task = driver.find_elements(By.CSS_SELECTOR, \".view\")[2]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^\n"}, "start": 1673097207201, "stop": 1673097207214}], "attachments": [{"source": "aad17c74-dc6e-4926-82e8-fc65ce94916c-attachment.png", "type": "image/png"}], "start": 1673097207154, "stop": 1673097207365, "uuid": "9c79a939-42f0-4ea6-bba1-42382ef6d3af", "historyId": "c14ef32e13854b5c934cc42dfeefc51d", "testCaseId": "ab1d7e1d77fb4a71b0068a8498b343ee", "fullName": "test_todo_app_allure.TestToDoActionsApp#test_tc02", "labels": [{"name": "suite", "value": "test_todo_app_allure"}, {"name": "subSuite", "value": "TestToDoActionsApp"}, {"name": "host", "value": "BarLaptop"}, {"name": "thread", "value": "4796-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_todo_app_allure"}]}